### ISSUE TITLE
Difference with https://github.com/php-serializers/ivory-serializer-benchmark ?

### ISSUE THREAD

**Issue by stof** [tsantos84/serializer-benchmark#18]
There is another PHP serializer benchmark which exists since a while at https://github.com/php-serializers/ivory-serializer-benchmark
What are the differences ? Would it make sense to join forces ?

**Comment by tsantos84** [comment]
Hi @stof. Actually the repository you've mentioned was recently forked by @goetas as the [original one](https://github.com/egeloen/ivory-serializer-benchmark) is not maintained anymore. When they started working on the forked one, @goetas asked me to add my serializer there and since then I've made some contribution as you can see on closed PRs. I agree with you that one central point is better to the community.

**Comment by stof** [comment]
So, is this repository now considered as obsolete in favor of https://github.com/php-serializers/ivory-serializer-benchmark ? If no, would it become obsolete in the future (for instance if this benchmark covers different cases which need to be contributed first) or would it still stay relevant ?

**Comment by tsantos84** [comment]
This repository can be considered obsolete when all its feature are implemented on the "official" one.
